### ISSUE TITLE
another great plugin!

### ISSUE THREAD

**Issue by XDqrkneZ** [Cansll/CkNameIt#1]
This is another great and useful plugin for my server. You might get this alot but, do you want to be the developer for my server? It will be paid

**Comment by Cansll** [comment]
Sry, I'm a student and I develop them only in my free time. All of them are simple and easy to develop, I don't need any reward for them. Thanks a lot and sorry for my poor English.

**Comment by XDqrkneZ** [comment]
alright, thanks for the time!
